within IBPSA.Fluid.PVTCollectors.Validation.BaseClasses;
model ElectricalPV
  "Model for PV panels using PV-oriented cell-temperature equations"

  parameter .Modelica.Units.SI.Irradiance G_STC=1000 "Irradiance at Standard Conditions (usualy 1000 W/m2)"
    annotation (Dialog(group="Characteristics of the photovoltaic panel"));
  parameter .Modelica.Units.SI.Power P_STC=370 "Power of one photovoltaic panel at Standard Conditions, usualy equal to power at Maximum Power Point (MPP)"
    annotation (Dialog(group="Characteristics of the photovoltaic panel"));
  parameter .Modelica.Units.SI.LinearTemperatureCoefficient beta=-0.0037 "Temperature coefficient of the photovoltaic panel(s)"
    annotation (Dialog(group="Characteristics of the photovoltaic panel"));
  parameter .Modelica.Units.SI.Efficiency eleLosFac=0.14 "Loss factor of the photovoltaic panel(s)"
    annotation (Dialog(group="Characteristics of the photovoltaic panel"));
  parameter Real n(min=.Modelica.Constants.small)=5 "Number of photovoltaic panels in the photovoltaic installation"
    annotation (Dialog(group="Characteristics of the photovoltaic installation"));
  parameter .Modelica.Units.SI.Efficiency module_efficiency=0.3 "Module efficiency of the photovoltaic installation";
  parameter .Modelica.Units.SI.Angle til=0.785 "Surface tilt of the photovoltaic installation (0°=horizontal, 90°=vertical)"
    annotation (Dialog(group="Characteristics of the photovoltaic installation"));
  parameter .Modelica.Units.SI.Angle azi=0 "Surface azimuth (0°=south, 90°=west, 180°=north, 270°=east)"
    annotation (Dialog(group="Characteristics of the photovoltaic installation"));

  .Modelica.Units.SI.Temperature T_cell "Cell temperature";
  .Modelica.Units.SI.Temperature T_cell_init "Initial cell temperature";
  .Modelica.Units.SI.TemperatureDifference T_diff "Temperature difference between the cell temperature and the reference temperature";
  .Modelica.Units.SI.Temperature T_noct_cell_adj "Adjusted nominal operating cell temperature";
  .Modelica.Units.SI.Efficiency eff_heat_loss "Heat loss coefficient of the PV panel";
  .Modelica.Units.SI.Efficiency eff_wind_loss "Wind loss coefficient of the PV panel";
  .Modelica.Units.SI.Velocity v_wind "Wind speed";
  .Modelica.Units.SI.Irradiance G "Total solar irradiance";

  .Modelica.Blocks.Interfaces.RealOutput P(quantity="Power", unit="W") "Power generated by the photovoltaic installation" annotation (Placement(transformation(extent={{10,-10},
            {-10,10}},
        rotation=180,
        origin={110,0})));
  .Modelica.Blocks.Sources.RealExpression solarPower(y=n*P_STC*G/G_STC*(1+beta*T_diff)*(1-eleLosFac))
    "Power generated by the photovoltaic installation" annotation (Placement(transformation(extent={{-10,-10},
            {10,10}})));

  .Modelica.Blocks.Interfaces.RealInput Gtil "Value of Real input" annotation (
      Placement(transformation(
        extent={{10,-10},{-10,10}},
        rotation=180,
        origin={-100,60})));
  .Modelica.Blocks.Interfaces.RealInput winSpe "Value of Real input" annotation (
     Placement(transformation(
        extent={{10,-10},{-10,10}},
        rotation=180,
        origin={-100,0})));
  .Modelica.Blocks.Interfaces.RealInput Tamb "Value of Real input" annotation (
      Placement(transformation(
        extent={{10,-10},{-10,10}},
        rotation=180,
        origin={-100,-60})));

protected
  final parameter .Modelica.Units.SI.Temperature Tref=25+273 "Reference temperature of the cell";
  final parameter .Modelica.Units.SI.Temperature Tnoct=49+273 "Nominal operating cell temperature";
  final parameter .Modelica.Units.SI.Velocity wind_init=9.5 "Reference wind speed";

equation
  assert(solarPower.y>=0, "Solar power must be positive");
  T_noct_cell_adj=Tnoct+6 "We assume an average distance between the panel and roof of 1.5-2.5 in.";
  T_cell_init=G/800*(T_noct_cell_adj-293) "in Kelvin";
  eff_heat_loss = 1-module_efficiency/0.9 "We assume a fixed tau alpha of 0.9";
  v_wind =winSpe;
  eff_wind_loss = wind_init/(5.7+3.8*0.51*v_wind);
  T_cell=Tamb + T_cell_init*eff_heat_loss*eff_wind_loss;
  G =Gtil;
  T_diff=T_cell-Tref;

  connect(solarPower.y, P) annotation (Line(points={{11,0},{110,0}},
                     color={0,0,127}));
    annotation (Dialog(group="Characteristics of the photovoltaic installation"),
    Icon(coordinateSystem(
        preserveAspectRatio=false,
        extent={{-100,-100},{100,100}},
        grid={1,1}), graphics={
        Line(points={{49,0},{100,0}},  color={0,0,0}),
        Polygon(
          points={{-80,-52},{-32,63},{78,63},{29,-52},{-80,-52}},
          smooth=Smooth.None,
          fillColor={205,203,203},
          fillPattern=FillPattern.Solid,
          pattern=LinePattern.None,
          lineColor={0,0,0}),
        Polygon(
          points={{-69,-45},{-57,-19},{-34,-19},{-45,-45},{-69,-45}},
          smooth=Smooth.None,
          fillColor={6,13,150},
          fillPattern=FillPattern.Solid,
          pattern=LinePattern.None),
        Polygon(
          points={{-53,-9},{-41,17},{-18,17},{-29,-9},{-53,-9}},
          smooth=Smooth.None,
          fillColor={6,13,150},
          fillPattern=FillPattern.Solid,
          pattern=LinePattern.None),
        Polygon(
          points={{-38,27},{-26,53},{-3,53},{-14,27},{-38,27}},
          smooth=Smooth.None,
          fillColor={6,13,150},
          fillPattern=FillPattern.Solid,
          pattern=LinePattern.None),
        Polygon(
          points={{-36,-45},{-24,-19},{-1,-19},{-12,-45},{-36,-45}},
          smooth=Smooth.None,
          fillColor={6,13,150},
          fillPattern=FillPattern.Solid,
          pattern=LinePattern.None),
        Polygon(
          points={{-20,-9},{-8,17},{15,17},{4,-9},{-20,-9}},
          smooth=Smooth.None,
          fillColor={6,13,150},
          fillPattern=FillPattern.Solid,
          pattern=LinePattern.None),
        Polygon(
          points={{-5,27},{7,53},{30,53},{19,27},{-5,27}},
          smooth=Smooth.None,
          fillColor={6,13,150},
          fillPattern=FillPattern.Solid,
          pattern=LinePattern.None),
        Polygon(
          points={{-3,-45},{9,-19},{32,-19},{21,-45},{-3,-45}},
          smooth=Smooth.None,
          fillColor={6,13,150},
          fillPattern=FillPattern.Solid,
          pattern=LinePattern.None),
        Polygon(
          points={{13,-9},{25,17},{48,17},{37,-9},{13,-9}},
          smooth=Smooth.None,
          fillColor={6,13,150},
          fillPattern=FillPattern.Solid,
          pattern=LinePattern.None),
        Polygon(
          points={{28,27},{40,53},{63,53},{52,27},{28,27}},
          smooth=Smooth.None,
          fillColor={6,13,150},
          fillPattern=FillPattern.Solid,
          pattern=LinePattern.None),
        Text(
          extent={{101,36},{123,10}},
          textColor={0,0,127},
          textString="P")}),
    Diagram(
        coordinateSystem(preserveAspectRatio=false)),
    Documentation(info="<html>
<p>
This model is an adapted PV-oriented electrical submodel based on the
<code>PVOrientedDCPower</code> model from the MoPED library
(Verleyen et&nbsp;al., 2022). It is included for <b>verification purposes</b>.
</p>
<p>
<b>Purpose / verification note:</b>
This submodel is used to demonstrate the bias introduced when applying
PV-only cell‑temperature equations to PVT collectors. Because unglazed
PVT collectors actively extract heat, their cell temperatures are typically
lower than those predicted by PV-based formulations, which results in overpredicting 
the PV cell temperature and underpedicting the electrical ouput of the PVT collector.
</p>
<h4>References</h4>
<ul>
<li>
Verleyen, L., Hermans, L., Arroyo, J., &amp; Helsen, L. (2022).
<i>Identifying technically feasible and effective solutions towards Positive Energy Districts (PEDs)</i>.
Proceedings of the Urban Energy in a Net Zero World Conference, Glasgow, Scotland.
(Source of the MoPED library electrical model).
</li>
</ul>
</html>",
revisions="<html>
<ul>
<li>
March 11, 2026, by Lone Meertens:<br/>
Adapted PV-oriented electrical model from the MoPED library for verification purposes only. 
This model is included to demonstrate the impact of using PV-based cell-temperature 
equations for PVT collectors. This is for <a href=\"https://github.com/open-ideas/IDEAS/issues/1473\">#1473</a>.
</li>
</ul>
</html>"));
end ElectricalPV;
