within IDEAS.Fluid.HeatExchangers.GroundHeatExchangers.Borefield.Data.Records;
record AggregationMatrix
  "Read the aggregation matrix from file. The data are generated by the model MutlipleBoreholes itself if the parameter saveAggMat=true"
  extends Modelica.Icons.Record;
  import SI = Modelica.SIunits;

  parameter Boolean rendering = false;
  parameter String name = "example";
  parameter String savePath=Modelica.Utilities.Files.loadResource("modelica://IDEAS/Fluid/HeatExchangers/GroundHeatExchangers/Borefield/Data/AggregationMatrix/");
  parameter String path="IDEAS.Fluid.HeatExchangers.GroundHeatExchangers.Borefield.Data.Records.AggregationMatrix";
  parameter Integer[2] matSize = Borefield.BaseClasses.Scripts.readAggregationMatrixSize(fileName=savePath+name+".mat",rendering=rendering);
  parameter Real[matSize[1],matSize[2]] aggMat = if rendering then {{1}} else readMatrix(fileName=savePath+name+".mat",matrixName="kappaMat",rows=matSize[1],columns=matSize[2]);
end AggregationMatrix;
