within IBPSA.Electrical.BaseClasses.PV.BaseClasses.Icons;
partial model partialPVIcon "Partial model for basic PV model icon"
  annotation (Icon(coordinateSystem(preserveAspectRatio=false, extent={{-100,
            -80},{100,80}}),                                    graphics={
    Rectangle(extent={{-50,80},{50,-78}},lineColor={215,215,215},fillColor={215,215,215},
            fillPattern =                                                                              FillPattern.Solid),
    Rectangle(extent={{-46,18},{-18,-10}},
                                        lineColor={0,0,255},fillColor={0,0,255},
            fillPattern =                                                                     FillPattern.Solid),
    Rectangle(extent={{-14,18},{14,-10}},
                                       lineColor={0,0,255},fillColor={0,0,255},
            fillPattern =                                                                    FillPattern.Solid),
    Rectangle(extent={{18,18},{46,-10}},
                                      lineColor={0,0,255},fillColor={0,0,255},
            fillPattern =                                                                   FillPattern.Solid),
    Rectangle(extent={{-46,-14},{-18,-42}},
                                          lineColor={0,0,255},fillColor={0,0,255},
            fillPattern =                                                                       FillPattern.Solid),
    Rectangle(extent={{-14,-14},{14,-42}},
                                         lineColor={0,0,255},fillColor={0,0,255},
            fillPattern =                                                                      FillPattern.Solid),
    Rectangle(extent={{18,-14},{46,-42}},
                                        lineColor={0,0,255},fillColor={0,0,255},
            fillPattern =                                                                     FillPattern.Solid),
    Rectangle(extent={{-46,-46},{-18,-74}},lineColor={0,0,255},fillColor={0,0,255},
            fillPattern =                                                                        FillPattern.Solid),
    Rectangle(extent={{-14,50},{14,22}},lineColor={0,0,255},fillColor={0,0,255},
            fillPattern =                                                                     FillPattern.Solid),
    Rectangle(extent={{18,50},{46,22}},lineColor={0,0,255},fillColor={0,0,255},
            fillPattern =                                                                    FillPattern.Solid),
    Rectangle(extent={{-46,50},{-18,22}},lineColor={0,0,255},fillColor={0,0,255},
            fillPattern =                                                                      FillPattern.Solid),
    Rectangle(extent={{-14,-46},{14,-74}},lineColor={0,0,255},fillColor={0,0,255},
            fillPattern =                                                                       FillPattern.Solid),
    Rectangle(extent={{18,-46},{46,-74}},lineColor={0,0,255},fillColor={0,0,255},
            fillPattern =                                                                      FillPattern.Solid),
                             Text(extent={{-44,84},{40,50}},  lineColor={0,0,255},textString= "%name")}),
      Diagram(coordinateSystem(preserveAspectRatio=false, extent={{-100,-80},
            {100,80}})));
end partialPVIcon;
