within IDEAS.Thermal.Components.GroundHeatExchanger.Borefield.BaseClasses.BoreHoles.Verification;
package Verification_Spitler_WetterDaP 
extends Icons.VerificationPackage;

end Verification_Spitler_WetterDaP;
